name: Push to Luarocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  pull_request: # Runs test install without uploading
  workflow_dispatch: # Allows to trigger manually

jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          labels: |
            neovim
            tree-sitter
          summary: A fork of tree-sitter-org, for use with the orgmode Neovim plugin
          template: .github/workflows/tree-sitter-orgmode.rockspec.template
